# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Repository\UserRepository:
        public: true

    repository.user_repository:
        alias: App\Repository\UserRepository

    App\Controller\Core\Repositories:
        public: true
        calls:
            - setUserRepository: ['@repository.user_repository']

    controller.core.repositories:
        alias: App\Controller\Core\Repositories

    App\Controller\Forms:
        public: true

    application.forms:
        alias: App\Controller\Forms

    App\Controller\System\SecurityController:
        public: true

    controller.system.security_controller:
        alias: App\Controller\System\SecurityController

    App\Controller\UserController:
        public: true

    controller.user_controller:
        alias: App\Controller\UserController

    App\Controller\Application:
        calls:
            - setTranslator: ['@translator']
            - setForms: ['@application.forms']
            - setRepositories: ['@controller.core.repositories']

    App\Controller\Core\Controllers:
        calls:
            - setSecurityController: ['@controller.system.security_controller']
            - setUserController: ['@controller.user_controller']
